package gsalaun.diverse

import kotlin.random.Random

interface IFuzz :
    IFuzzNumbers,
    IFuzzPersons,
    IFuzzDatesAndTime,
    IFuzzStrings,
    IFuzzTypes,
    IFuzzUuid,
    IFuzzFromCollections,
    IFuzzLorem,
    IFuzzAddress {
    /**
     * Gets a Random instance to use if you want your extensible Fuzzer to be deterministic when providing a seed.
     */
    val random: Random

    /**
     * Returns a {@link IFuzz}> instance that you can use to generate always different values from now
     * (i.e. values that will be generated by this very specific {@link IFuzz} instance only).
     * In other word, a {@link IFuzz} instance that will never return twice the same value (whatever the method called).
     *
     * @return A {@link IFuzz} instance that will never return twice the same value (whatever the method called).
     */
    fun generateNoDuplicationFuzzer(): IFuzz

    /**
     * Flips a coin
     *
     * @return <b>True</b> if Heads; <b>False</b> otherwise (i.e. Tails).
     */
    fun headsOrTails(): Boolean
}
