package gsalaun.diverse.persons

object Female {

    private var _firstNames: List<String> = emptyList()

    /**
     * Gets all the female first names possibly used by the lib.
     */
    val firstNames: List<String>
        get() {
            if (_firstNames.isEmpty()) {
                _firstNames = contextualizedFirstNames
                    .filter { it.firstName.isNotBlank() }
                    .map { it.firstName }
                    .distinct()
            }

            return _firstNames
        }

    /**
     * Gets all the {@link ContextualizedFirstName} instances possibly used by the lib.
     */
    val contextualizedFirstNames: List<ContextualizedFirstName>
        get() {
            return Female._contextualizedFirstNames
        }

    // TODO Maybe use a json instead
    private val _contextualizedFirstNames: List<ContextualizedFirstName> = listOf(
        ContextualizedFirstName("Aaliyah", Continent.AFRICA),
        ContextualizedFirstName("Alyssa", Continent.AFRICA),
        ContextualizedFirstName("Bintu", Continent.AFRICA),
        ContextualizedFirstName("Jemila", Continent.AFRICA),
        ContextualizedFirstName("Jendayi", Continent.AFRICA),
        ContextualizedFirstName("Keisha", Continent.AFRICA),
        ContextualizedFirstName("Laila", Continent.AFRICA),
        ContextualizedFirstName("Abeba", Continent.AFRICA),
        ContextualizedFirstName("Aminata", Continent.AFRICA),
        ContextualizedFirstName("Isis", Continent.AFRICA),
        ContextualizedFirstName("Makeba", Continent.AFRICA),
        ContextualizedFirstName("Malika", Continent.AFRICA),
        ContextualizedFirstName("Rokhaya", Continent.AFRICA),
        ContextualizedFirstName("Fatoumata", Continent.AFRICA),
        ContextualizedFirstName("Awa", Continent.AFRICA),
        ContextualizedFirstName("Aissatou", Continent.AFRICA),
        ContextualizedFirstName("Mariama", Continent.AFRICA),
        ContextualizedFirstName("Khadidiatou", Continent.AFRICA),
        ContextualizedFirstName("Aida", Continent.AFRICA),
        ContextualizedFirstName("Ramatoulaye", Continent.AFRICA),
        ContextualizedFirstName("Rama", Continent.AFRICA),
        ContextualizedFirstName("Nzinga", Continent.AFRICA),
        ContextualizedFirstName("Nakeisha", Continent.AFRICA),
        ContextualizedFirstName("Zahara", Continent.AFRICA),
        ContextualizedFirstName("Zuri", Continent.AFRICA),
        ContextualizedFirstName("Kwame", Continent.AFRICA),
        ContextualizedFirstName("Amber", Continent.AFRICA),
        ContextualizedFirstName("Qwara", Continent.AFRICA),
        ContextualizedFirstName("Nyofu", Continent.AFRICA),
        ContextualizedFirstName("Ekundayo", Continent.AFRICA),
        ContextualizedFirstName("Kione", Continent.AFRICA),
        ContextualizedFirstName("Thenjiwe", Continent.AFRICA),
        ContextualizedFirstName("Johari", Continent.AFRICA),
        ContextualizedFirstName("Tene", Continent.AFRICA),
        ContextualizedFirstName("Nimeesha", Continent.AFRICA),
        ContextualizedFirstName("Nkechi", Continent.AFRICA),

        ContextualizedFirstName("Rim", Continent.AFRICA),
        ContextualizedFirstName("Nora", Continent.AFRICA),
        ContextualizedFirstName("Sarah", Continent.AFRICA),
        ContextualizedFirstName("Fatima", Continent.AFRICA),
        ContextualizedFirstName("Noûr", Continent.AFRICA),
        ContextualizedFirstName("Louna", Continent.AFRICA),
        ContextualizedFirstName("Maïssa", Continent.AFRICA),
        ContextualizedFirstName("Kenza", Continent.AFRICA),
        ContextualizedFirstName("Selma", Continent.AFRICA),
        ContextualizedFirstName("Jasmine", Continent.AFRICA),
        ContextualizedFirstName("Janna", Continent.AFRICA),
        ContextualizedFirstName("Mériem", Continent.AFRICA),
        ContextualizedFirstName("Zayneb", Continent.AFRICA),
        ContextualizedFirstName("Khadija", Continent.AFRICA),
        ContextualizedFirstName("Iman", Continent.AFRICA),
        ContextualizedFirstName("Mouna", Continent.AFRICA),
        ContextualizedFirstName("Ayisha", Continent.AFRICA),
        ContextualizedFirstName("Aicha", Continent.AFRICA),
        ContextualizedFirstName("Jamila", Continent.AFRICA),
        ContextualizedFirstName("Farida", Continent.AFRICA),
        ContextualizedFirstName("Kelthouma", Continent.AFRICA),
        ContextualizedFirstName("Samia", Continent.AFRICA),
        ContextualizedFirstName("Asma", Continent.AFRICA),
        ContextualizedFirstName("Leila", Continent.AFRICA),

        ContextualizedFirstName("Solveig", Continent.ANTARCTICA),
        ContextualizedFirstName("Freja", Continent.ANTARCTICA),
        ContextualizedFirstName("Kirsten", Continent.ANTARCTICA),
        ContextualizedFirstName("Mette", Continent.ANTARCTICA),
        ContextualizedFirstName("Liv", Continent.ANTARCTICA),
        ContextualizedFirstName("Erika", Continent.ANTARCTICA),
        ContextualizedFirstName("Maja", Continent.ANTARCTICA),
        ContextualizedFirstName("Ida", Continent.ANTARCTICA),
        ContextualizedFirstName("Anouk", Continent.ANTARCTICA),
        ContextualizedFirstName("Johanna", Continent.ANTARCTICA),
        ContextualizedFirstName("Mathilda", Continent.ANTARCTICA),
        ContextualizedFirstName("Sigrid", Continent.ANTARCTICA),
        ContextualizedFirstName("Anya", Continent.ANTARCTICA),
        ContextualizedFirstName("Kristina", Continent.ANTARCTICA),
        ContextualizedFirstName("Gefjun", Continent.ANTARCTICA),
        ContextualizedFirstName("Edda", Continent.ANTARCTICA),
        ContextualizedFirstName("Byrget", Continent.ANTARCTICA),
        ContextualizedFirstName("Frigga", Continent.ANTARCTICA),
        ContextualizedFirstName("Norne", Continent.ANTARCTICA),
        ContextualizedFirstName("Lidweina", Continent.ANTARCTICA),
        ContextualizedFirstName("Signilde", Continent.ANTARCTICA),
        ContextualizedFirstName("Brendette", Continent.ANTARCTICA),
        ContextualizedFirstName("Trini", Continent.ANTARCTICA),
        ContextualizedFirstName("Asti", Continent.ANTARCTICA),
        ContextualizedFirstName("Astryr", Continent.ANTARCTICA),
        ContextualizedFirstName("Gefjun", Continent.ANTARCTICA),
        ContextualizedFirstName("Erna", Continent.ANTARCTICA),
        ContextualizedFirstName("Ursule", Continent.ANTARCTICA),
        ContextualizedFirstName("Solveig", Continent.ANTARCTICA),
        ContextualizedFirstName("Erike", Continent.ANTARCTICA),

        ContextualizedFirstName("Ahnjong", Continent.ASIA),
        ContextualizedFirstName("Kyeol", Continent.ASIA),
        ContextualizedFirstName("Ja-kyung", Continent.ASIA),
        ContextualizedFirstName("Jeong-ja", Continent.ASIA),
        ContextualizedFirstName("Ji-yeon", Continent.ASIA),
        ContextualizedFirstName("Jung-sook", Continent.ASIA),
        ContextualizedFirstName("Bae", Continent.ASIA),
        ContextualizedFirstName("Bitna", Continent.ASIA),
        ContextualizedFirstName("Bong-Cha", Continent.ASIA),
        ContextualizedFirstName("Byeol", Continent.ASIA),
        ContextualizedFirstName("Choon-He", Continent.ASIA),
        ContextualizedFirstName("Chul", Continent.ASIA),
        ContextualizedFirstName("Dae", Continent.ASIA),
        ContextualizedFirstName("Eun-Kyung", Continent.ASIA),
        ContextualizedFirstName("Goo", Continent.ASIA),
        ContextualizedFirstName("Hei-Ran", Continent.ASIA),
        ContextualizedFirstName("Hyo", Continent.ASIA),

        ContextualizedFirstName("Diễm Hạnh", Continent.ASIA),
        ContextualizedFirstName("Duong Liễu", Continent.ASIA),
        ContextualizedFirstName("Mai Lan", Continent.ASIA),
        ContextualizedFirstName("Mây", Continent.ASIA),
        ContextualizedFirstName("My Lê", Continent.ASIA),
        ContextualizedFirstName("Tuong Vi", Continent.ASIA),
        ContextualizedFirstName("Vân", Continent.ASIA),
        ContextualizedFirstName("Xuân", Continent.ASIA),
        ContextualizedFirstName("Khuong", Continent.ASIA),
        ContextualizedFirstName("Nhu", Continent.ASIA),
        ContextualizedFirstName("Cai", Continent.ASIA),
        ContextualizedFirstName("Nhung", Continent.ASIA),
        ContextualizedFirstName("Thuong", Continent.ASIA),

        ContextualizedFirstName("Zhang", Continent.ASIA),
        ContextualizedFirstName("Mei", Continent.ASIA),
        ContextualizedFirstName("Lin", Continent.ASIA),
        ContextualizedFirstName("Wen", Continent.ASIA),
        ContextualizedFirstName("Xian", Continent.ASIA),
        ContextualizedFirstName("Jiao", Continent.ASIA),
        ContextualizedFirstName("Lan", Continent.ASIA),
        ContextualizedFirstName("Chan", Continent.ASIA),
        ContextualizedFirstName("Li", Continent.ASIA),
        ContextualizedFirstName("Xiu", Continent.ASIA),
        ContextualizedFirstName("Li Mei", Continent.ASIA),
        ContextualizedFirstName("Zhi", Continent.ASIA),
        ContextualizedFirstName("Meiling", Continent.ASIA),
        ContextualizedFirstName("Qi", Continent.ASIA),
        ContextualizedFirstName("Bao", Continent.ASIA),
        ContextualizedFirstName("Chen", Continent.ASIA),
        ContextualizedFirstName("Shu Fang", Continent.ASIA),
        ContextualizedFirstName("Li Ming", Continent.ASIA),
        ContextualizedFirstName("Xing Xing", Continent.ASIA),
        ContextualizedFirstName("Yue", Continent.ASIA),
        ContextualizedFirstName("Qiao", Continent.ASIA),

        ContextualizedFirstName("Avigail", Continent.ASIA),
        ContextualizedFirstName("Bayla", Continent.ASIA),
        ContextualizedFirstName("Esther", Continent.ASIA),
        ContextualizedFirstName("Ednah", Continent.ASIA),
        ContextualizedFirstName("Ashra", Continent.ASIA),
        ContextualizedFirstName("Zakyla", Continent.ASIA),
        ContextualizedFirstName("Shalvah", Continent.ASIA),
        ContextualizedFirstName("Misha", Continent.ASIA),
        ContextualizedFirstName("Malka", Continent.ASIA),
        ContextualizedFirstName("Meirav", Continent.ASIA),
        ContextualizedFirstName("Yael", Continent.ASIA),
        ContextualizedFirstName("Eliszabeth", Continent.ASIA),
        ContextualizedFirstName("Doveva", Continent.ASIA),
        ContextualizedFirstName("Nataniya", Continent.ASIA),
        ContextualizedFirstName("Samarah", Continent.ASIA),
        ContextualizedFirstName("Dinah", Continent.ASIA),

        ContextualizedFirstName("Kamini", Continent.ASIA),
        ContextualizedFirstName("Akshara", Continent.ASIA),
        ContextualizedFirstName("Amruta", Continent.ASIA),
        ContextualizedFirstName("Deepa", Continent.ASIA),
        ContextualizedFirstName("Ishani", Continent.ASIA),
        ContextualizedFirstName("Lajita", Continent.ASIA),
        ContextualizedFirstName("Rajeshri", Continent.ASIA),
        ContextualizedFirstName("Suhani", Continent.ASIA),
        ContextualizedFirstName("Indu", Continent.ASIA),
        ContextualizedFirstName("Vasatika", Continent.ASIA),
        ContextualizedFirstName("Trisha", Continent.ASIA),
        ContextualizedFirstName("Devi", Continent.ASIA),
        ContextualizedFirstName("Usha", Continent.ASIA),
        ContextualizedFirstName("Shanti", Continent.ASIA),
        ContextualizedFirstName("Ameeta", Continent.ASIA),
        ContextualizedFirstName("Indira", Continent.ASIA),
        ContextualizedFirstName("Shyla", Continent.ASIA),
        ContextualizedFirstName("Lajita", Continent.ASIA),
        ContextualizedFirstName("Guri", Continent.ASIA),
        ContextualizedFirstName("Sunita", Continent.ASIA),
        ContextualizedFirstName("Geeta", Continent.ASIA),
        ContextualizedFirstName("Sunila", Continent.ASIA),
        ContextualizedFirstName("Chandrika", Continent.ASIA),
        ContextualizedFirstName("Shantee", Continent.ASIA),
        ContextualizedFirstName("Urja", Continent.ASIA),
        ContextualizedFirstName("Arundhati", Continent.ASIA),
        ContextualizedFirstName("Kirti", Continent.ASIA),

        ContextualizedFirstName("Louise", Continent.EUROPE),
        ContextualizedFirstName("Audrey", Continent.EUROPE),
        ContextualizedFirstName("Laurence", Continent.EUROPE),
        ContextualizedFirstName("Christine", Continent.EUROPE),
        ContextualizedFirstName("Marie", Continent.EUROPE),
        ContextualizedFirstName("Nathalie", Continent.EUROPE),
        ContextualizedFirstName("Sophie", Continent.EUROPE),
        ContextualizedFirstName("Karine", Continent.EUROPE),
        ContextualizedFirstName("Ève", Continent.EUROPE),
        ContextualizedFirstName("Noëlla", Continent.EUROPE),
        ContextualizedFirstName("Sandrine", Continent.EUROPE),
        ContextualizedFirstName("Marie-Hélène", Continent.EUROPE),
        ContextualizedFirstName("Iris", Continent.EUROPE),
        ContextualizedFirstName("Anne-Marie", Continent.EUROPE),
        ContextualizedFirstName("Fleur", Continent.EUROPE),
        ContextualizedFirstName("Noëlla", Continent.EUROPE),
        ContextualizedFirstName("Nicole", Continent.EUROPE),
        ContextualizedFirstName("Annabelle", Continent.EUROPE),
        ContextualizedFirstName("Anaïs", Continent.EUROPE),
        ContextualizedFirstName("Noémie", Continent.EUROPE),
        ContextualizedFirstName("Catherine", Continent.EUROPE),
        ContextualizedFirstName("Clarence", Continent.EUROPE),
        ContextualizedFirstName("Hélène", Continent.EUROPE),
        ContextualizedFirstName("Laura", Continent.EUROPE),
        ContextualizedFirstName("Lydia", Continent.EUROPE),
        ContextualizedFirstName("Emma", Continent.EUROPE),
        ContextualizedFirstName("Thaïs", Continent.EUROPE),
        ContextualizedFirstName("Mathilde", Continent.EUROPE),
        ContextualizedFirstName("Réjane", Continent.EUROPE),
        ContextualizedFirstName("Clémence", Continent.EUROPE),

        ContextualizedFirstName("Marta", Continent.EUROPE),
        ContextualizedFirstName("Tsvetomira", Continent.EUROPE),
        ContextualizedFirstName("Valombrosa", Continent.EUROPE),
        ContextualizedFirstName("Beonca", Continent.EUROPE),
        ContextualizedFirstName("Enrica", Continent.EUROPE),
        ContextualizedFirstName("Giovanna", Continent.EUROPE),
        ContextualizedFirstName("Gioconda", Continent.EUROPE),
        ContextualizedFirstName("Chiara", Continent.EUROPE),
        ContextualizedFirstName("Donna-Marie", Continent.EUROPE),
        ContextualizedFirstName("Hildagard", Continent.EUROPE),
        ContextualizedFirstName("Ulrike", Continent.EUROPE),
        ContextualizedFirstName("Allayne", Continent.EUROPE),
        ContextualizedFirstName("Carolein", Continent.EUROPE),
        ContextualizedFirstName("Jocelynn", Continent.EUROPE),

        ContextualizedFirstName("Beata", Continent.EUROPE),
        ContextualizedFirstName("Anja", Continent.EUROPE),
        ContextualizedFirstName("Maya", Continent.EUROPE),
        ContextualizedFirstName("Maëla", Continent.EUROPE),
        ContextualizedFirstName("Marija", Continent.EUROPE),
        ContextualizedFirstName("Tanja", Continent.EUROPE),
        ContextualizedFirstName("Anneke", Continent.EUROPE),
        ContextualizedFirstName("Antje", Continent.EUROPE),
        ContextualizedFirstName("Heike", Continent.EUROPE),
        ContextualizedFirstName("Sofie", Continent.EUROPE),
        ContextualizedFirstName("Birgit", Continent.EUROPE),
        ContextualizedFirstName("Yarmilla", Continent.EUROPE),
        ContextualizedFirstName("Wonnda", Continent.EUROPE),
        ContextualizedFirstName("Miri", Continent.EUROPE),

        ContextualizedFirstName("Nichelle", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Nancy", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Rebecca", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Julie", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Vanessa", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Darlene", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Naomi", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Shayna", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Sarah", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Emily", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Shana", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Zoe", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Chloe", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Ella", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Hailey", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Karen", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Jenue", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Janelle", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Diantha", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Lacoya", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Rondell", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Davonne", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Gisbelle", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Janeese", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Ronalee", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Shierlyn", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Lashae", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Kaylinn", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Tandice", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Candice", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Danedria", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Revonda", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Deloise", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Errin", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Jariah", Continent.NORTH_AMERICA),

        ContextualizedFirstName("Facunda", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Penelope", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Sierra", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Dhalia", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Francesca", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Valentina", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Ximena", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Isabella", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Renata", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Valeria", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Andrijana", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Camelia", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Emanuele", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Maria Eduarda", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Beatriz", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Romina", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Jolanta", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Carmen", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Jacynthe", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Aintzane", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Yolanda", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Luzita", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Manuela", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Ramohna", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Reynalda", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Pepa", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Roja", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Neina", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Maffalda", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Javiera", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Delora", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Estelita", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Orazia", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Chiquin", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Gabriela", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Lluisa", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Yanamarie", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Estefania", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Pepita", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Inocenta", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Cesara", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Natalita", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Juanita", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Soledada", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Natividad", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Chiquita", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Landa", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Itxaro", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Racquel", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Mendi", Continent.SOUTH_AMERICA),

        ContextualizedFirstName("Abigail", Continent.AUSTRALIA),
        ContextualizedFirstName("Addison", Continent.AUSTRALIA),
        ContextualizedFirstName("Alinta", Continent.AUSTRALIA),
        ContextualizedFirstName("Aurora", Continent.AUSTRALIA),
        ContextualizedFirstName("Charlotte", Continent.AUSTRALIA),
        ContextualizedFirstName("Daisy", Continent.AUSTRALIA),
        ContextualizedFirstName("Eleanor", Continent.AUSTRALIA),
        ContextualizedFirstName("Olivia", Continent.AUSTRALIA),
        ContextualizedFirstName("Grace", Continent.AUSTRALIA),
        ContextualizedFirstName("Harper", Continent.AUSTRALIA),
        ContextualizedFirstName("Ava", Continent.AUSTRALIA),
        ContextualizedFirstName("Alexandra", Continent.AUSTRALIA),
        ContextualizedFirstName("Alexis", Continent.AUSTRALIA),
        ContextualizedFirstName("Alinta", Continent.AUSTRALIA),
        ContextualizedFirstName("Claire", Continent.AUSTRALIA),
        ContextualizedFirstName("Eden", Continent.AUSTRALIA),
        ContextualizedFirstName("Eleanor", Continent.AUSTRALIA),
        ContextualizedFirstName("Elsie", Continent.AUSTRALIA),
        ContextualizedFirstName("Evelyn", Continent.AUSTRALIA),
        ContextualizedFirstName("Georgia", Continent.AUSTRALIA),
        ContextualizedFirstName("Imogen", Continent.AUSTRALIA),
        ContextualizedFirstName("Jessica", Continent.AUSTRALIA),

        ContextualizedFirstName("Taworri", Continent.AUSTRALIA),
        ContextualizedFirstName("Tyipa", Continent.AUSTRALIA),
        ContextualizedFirstName("Yamparti", Continent.AUSTRALIA),
        ContextualizedFirstName("Kaawa", Continent.AUSTRALIA),
        ContextualizedFirstName("Yoyko", Continent.AUSTRALIA),
        ContextualizedFirstName("Isley", Continent.AUSTRALIA),
        ContextualizedFirstName("Elandra", Continent.AUSTRALIA),
        ContextualizedFirstName("Akuna", Continent.AUSTRALIA),

        ContextualizedFirstName("Vaiana", Continent.AUSTRALIA),
        ContextualizedFirstName("Tahia", Continent.AUSTRALIA),
        ContextualizedFirstName("Manutea", Continent.AUSTRALIA),
        ContextualizedFirstName("Poe", Continent.AUSTRALIA),
        ContextualizedFirstName("Heirani", Continent.AUSTRALIA),
        ContextualizedFirstName("Vanina", Continent.AUSTRALIA),
        ContextualizedFirstName("Moeata", Continent.AUSTRALIA),
    )
}
