package gsalaun.diverse.persons

object Male {

    private var _firstNames: List<String> = emptyList()

    /**
     * Gets all the female first names possibly used by the lib.
     */
    val firstNames: List<String>
        get() {
            if (_firstNames.isEmpty()) {
                _firstNames = contextualizedFirstNames
                    .filter { it.firstName.isNotBlank() }
                    .map { it.firstName }
                    .distinct()
            }

            return _firstNames
        }

    /**
     * Gets all the {@link ContextualizedFirstName} instances possibly used by the lib.
     */
    val contextualizedFirstNames: List<ContextualizedFirstName>
        get() {
            return _contextualizedFirstNames
        }

    // TODO Maybe use a json instead
    private val _contextualizedFirstNames: List<ContextualizedFirstName> = listOf(
        ContextualizedFirstName("Moussa", Continent.AFRICA),
        ContextualizedFirstName("Djibril", Continent.AFRICA),
        ContextualizedFirstName("Issa", Continent.AFRICA),
        ContextualizedFirstName("Sékou", Continent.AFRICA),
        ContextualizedFirstName("Djiby", Continent.AFRICA),
        ContextualizedFirstName("Koffi", Continent.AFRICA),
        ContextualizedFirstName("Mahdi", Continent.AFRICA),
        ContextualizedFirstName("Demba", Continent.AFRICA),
        ContextualizedFirstName("Mamadou", Continent.AFRICA),
        ContextualizedFirstName("Atef", Continent.AFRICA),
        ContextualizedFirstName("Ousmane", Continent.AFRICA),
        ContextualizedFirstName("Ladji", Continent.AFRICA),
        ContextualizedFirstName("Aly-Bocar", Continent.AFRICA),
        ContextualizedFirstName("Uélé", Continent.AFRICA),
        ContextualizedFirstName("Kinfe", Continent.AFRICA),
        ContextualizedFirstName("Mugisa", Continent.AFRICA),
        ContextualizedFirstName("Kimoni", Continent.AFRICA),
        ContextualizedFirstName("Simba", Continent.AFRICA),
        ContextualizedFirstName("Kwanza", Continent.AFRICA),
        ContextualizedFirstName("Olamide", Continent.AFRICA),
        ContextualizedFirstName("Bahari", Continent.AFRICA),
        ContextualizedFirstName("Dzigbode", Continent.AFRICA),
        ContextualizedFirstName("Sekou", Continent.AFRICA),
        ContextualizedFirstName("Dakarai", Continent.AFRICA),
        ContextualizedFirstName("Nuru", Continent.AFRICA),
        ContextualizedFirstName("Okal", Continent.AFRICA),
        ContextualizedFirstName("Sadioba", Continent.AFRICA),
        ContextualizedFirstName("Thierno", Continent.AFRICA),
        ContextualizedFirstName("Cheikh", Continent.AFRICA),
        ContextualizedFirstName("Babacar", Continent.AFRICA),
        ContextualizedFirstName("Aliou", Continent.AFRICA),
        ContextualizedFirstName("Adama", Continent.AFRICA),
        ContextualizedFirstName("Malik", Continent.AFRICA),
        ContextualizedFirstName("Lamine", Continent.AFRICA),

        ContextualizedFirstName("Yazid", Continent.AFRICA),
        ContextualizedFirstName("Ali", Continent.AFRICA),
        ContextualizedFirstName("Karim", Continent.AFRICA),
        ContextualizedFirstName("Mohammed", Continent.AFRICA),
        ContextualizedFirstName("Mehdi", Continent.AFRICA),
        ContextualizedFirstName("Noam", Continent.AFRICA),
        ContextualizedFirstName("Jalil", Continent.AFRICA),
        ContextualizedFirstName("Malik", Continent.AFRICA),
        ContextualizedFirstName("Hakim", Continent.AFRICA),
        ContextualizedFirstName("Hisham", Continent.AFRICA),
        ContextualizedFirstName("Abdourahmane", Continent.AFRICA),
        ContextualizedFirstName("Youssef", Continent.AFRICA),
        ContextualizedFirstName("Lounes", Continent.AFRICA),
        ContextualizedFirstName("Khaled", Continent.AFRICA),
        ContextualizedFirstName("Lahcen", Continent.AFRICA),
        ContextualizedFirstName("Sadiq", Continent.AFRICA),
        ContextualizedFirstName("Akmal", Continent.AFRICA),
        ContextualizedFirstName("Jemahl", Continent.AFRICA),
        ContextualizedFirstName("Abu Bakr", Continent.AFRICA),
        ContextualizedFirstName("Waleed", Continent.AFRICA),
        ContextualizedFirstName("Jemaal", Continent.AFRICA),
        ContextualizedFirstName("Adil", Continent.AFRICA),
        ContextualizedFirstName("Naseer", Continent.AFRICA),
        ContextualizedFirstName("Abdallah", Continent.AFRICA),

        ContextualizedFirstName("Aleksander", Continent.ANTARCTICA),
        ContextualizedFirstName("Ansgar", Continent.ANTARCTICA),
        ContextualizedFirstName("Einar", Continent.ANTARCTICA),
        ContextualizedFirstName("Casper", Continent.ANTARCTICA),
        ContextualizedFirstName("Eirik", Continent.ANTARCTICA),
        ContextualizedFirstName("Enok", Continent.ANTARCTICA),
        ContextualizedFirstName("Espen", Continent.ANTARCTICA),
        ContextualizedFirstName("Frans", Continent.ANTARCTICA),
        ContextualizedFirstName("Gjurd", Continent.ANTARCTICA),
        ContextualizedFirstName("Gunne", Continent.ANTARCTICA),
        ContextualizedFirstName("Olle", Continent.ANTARCTICA),
        ContextualizedFirstName("Oluf", Continent.ANTARCTICA),
        ContextualizedFirstName("Bjorn", Continent.ANTARCTICA),
        ContextualizedFirstName("Hjalmer", Continent.ANTARCTICA),
        ContextualizedFirstName("Kris", Continent.ANTARCTICA),
        ContextualizedFirstName("Gustavus", Continent.ANTARCTICA),
        ContextualizedFirstName("Sven", Continent.ANTARCTICA),
        ContextualizedFirstName("Skeet", Continent.ANTARCTICA),
        ContextualizedFirstName("Heimdall", Continent.ANTARCTICA),
        ContextualizedFirstName("Osmunde", Continent.ANTARCTICA),
        ContextualizedFirstName("Jensson", Continent.ANTARCTICA),
        ContextualizedFirstName("Ragnar", Continent.ANTARCTICA),
        ContextualizedFirstName("Hallverd", Continent.ANTARCTICA),
        ContextualizedFirstName("Vondell", Continent.ANTARCTICA),
        ContextualizedFirstName("Eyulf", Continent.ANTARCTICA),
        ContextualizedFirstName("Hagan", Continent.ANTARCTICA),
        ContextualizedFirstName("Eskel", Continent.ANTARCTICA),
        ContextualizedFirstName("Tuve", Continent.ANTARCTICA),

        ContextualizedFirstName("Yi", Continent.ASIA),
        ContextualizedFirstName("Jian", Continent.ASIA),
        ContextualizedFirstName("Jin", Continent.ASIA),
        ContextualizedFirstName("Cheng", Continent.ASIA),
        ContextualizedFirstName("Tian", Continent.ASIA),
        ContextualizedFirstName("Zhen", Continent.ASIA),
        ContextualizedFirstName("Chao", Continent.ASIA),
        ContextualizedFirstName("Guang", Continent.ASIA),
        ContextualizedFirstName("Yu Jie", Continent.ASIA),
        ContextualizedFirstName("Shui", Continent.ASIA),
        ContextualizedFirstName("Qiao", Continent.ASIA),
        ContextualizedFirstName("Tao", Continent.ASIA),
        ContextualizedFirstName("Shing", Continent.ASIA),
        ContextualizedFirstName("Mu", Continent.ASIA),
        ContextualizedFirstName("Xing Xing", Continent.ASIA),

        ContextualizedFirstName("Ba-Thong", Continent.ASIA),
        ContextualizedFirstName("Hoàng", Continent.ASIA),
        ContextualizedFirstName("Bao", Continent.ASIA),
        ContextualizedFirstName("Hoà", Continent.ASIA),
        ContextualizedFirstName("Quang", Continent.ASIA),
        ContextualizedFirstName("Toàn", Continent.ASIA),
        ContextualizedFirstName("Vinh", Continent.ASIA),
        ContextualizedFirstName("Khoi", Continent.ASIA),
        ContextualizedFirstName("Thuyet", Continent.ASIA),
        ContextualizedFirstName("Trung", Continent.ASIA),
        ContextualizedFirstName("Binh", Continent.ASIA),
        ContextualizedFirstName("Loc", Continent.ASIA),

        ContextualizedFirstName("Kim", Continent.ASIA),
        ContextualizedFirstName("Kwon", Continent.ASIA),
        ContextualizedFirstName("Hwang", Continent.ASIA),

        ContextualizedFirstName("Daichi", Continent.ASIA),
        ContextualizedFirstName("Akira", Continent.ASIA),
        ContextualizedFirstName("Daisuke", Continent.ASIA),
        ContextualizedFirstName("Fumihiro", Continent.ASIA),
        ContextualizedFirstName("Hikaru", Continent.ASIA),
        ContextualizedFirstName("Hansuke", Continent.ASIA),
        ContextualizedFirstName("Soske", Continent.ASIA),
        ContextualizedFirstName("Kōhei", Continent.ASIA),
        ContextualizedFirstName("Izuku", Continent.ASIA),
        ContextualizedFirstName("Katsuki", Continent.ASIA),

        ContextualizedFirstName("Mentari", Continent.ASIA),
        ContextualizedFirstName("Timur", Continent.ASIA),
        ContextualizedFirstName("Eko", Continent.ASIA),
        ContextualizedFirstName("Gemi", Continent.ASIA),
        ContextualizedFirstName("Harta", Continent.ASIA),

        ContextualizedFirstName("Aslan", Continent.ASIA),
        ContextualizedFirstName("Eren", Continent.ASIA),
        ContextualizedFirstName("Enis", Continent.ASIA),
        ContextualizedFirstName("Kaan", Continent.ASIA),
        ContextualizedFirstName("Aylan", Continent.ASIA),
        ContextualizedFirstName("Mehmet", Continent.ASIA),
        ContextualizedFirstName("Ömer", Continent.ASIA),
        ContextualizedFirstName("Abraham", Continent.ASIA),
        ContextualizedFirstName("Elias", Continent.ASIA),
        ContextualizedFirstName("Nataniel", Continent.ASIA),
        ContextualizedFirstName("Joab", Continent.ASIA),
        ContextualizedFirstName("Davy", Continent.ASIA),
        ContextualizedFirstName("Davyd", Continent.ASIA),
        ContextualizedFirstName("Daneal", Continent.ASIA),
        ContextualizedFirstName("Shoval", Continent.ASIA),
        ContextualizedFirstName("Jarrad", Continent.ASIA),
        ContextualizedFirstName("Jarrad", Continent.ASIA),
        ContextualizedFirstName("Yannick", Continent.ASIA),

        ContextualizedFirstName("Kumar", Continent.ASIA),
        ContextualizedFirstName("Arjun", Continent.ASIA),
        ContextualizedFirstName("Aadesh", Continent.ASIA),
        ContextualizedFirstName("Abhimanyu", Continent.ASIA),
        ContextualizedFirstName("Adrith", Continent.ASIA),
        ContextualizedFirstName("Akshay", Continent.ASIA),
        ContextualizedFirstName("Kamal", Continent.ASIA),
        ContextualizedFirstName("Lavish", Continent.ASIA),
        ContextualizedFirstName("Krishna", Continent.ASIA),
        ContextualizedFirstName("Rajiv", Continent.ASIA),
        ContextualizedFirstName("Sumedh", Continent.ASIA),
        ContextualizedFirstName("Jaycarran", Continent.ASIA),
        ContextualizedFirstName("Ashok", Continent.ASIA),
        ContextualizedFirstName("Shivedutt", Continent.ASIA),
        ContextualizedFirstName("Mahavira", Continent.ASIA),
        ContextualizedFirstName("Saariq", Continent.ASIA),
        ContextualizedFirstName("Umed", Continent.ASIA),
        ContextualizedFirstName("Sareek", Continent.ASIA),
        ContextualizedFirstName("Nirav", Continent.ASIA),
        ContextualizedFirstName("Ashvik", Continent.ASIA),
        ContextualizedFirstName("Ganesa", Continent.ASIA),
        ContextualizedFirstName("Ranjit", Continent.ASIA),
        ContextualizedFirstName("Sanjay", Continent.ASIA),
        ContextualizedFirstName("Govind", Continent.ASIA),

        ContextualizedFirstName("Achille", Continent.EUROPE),
        ContextualizedFirstName("Markus", Continent.EUROPE),
        ContextualizedFirstName("Wolfgang", Continent.EUROPE),
        ContextualizedFirstName("Lukas", Continent.EUROPE),
        ContextualizedFirstName("Karl", Continent.EUROPE),
        ContextualizedFirstName("Édouard", Continent.EUROPE),
        ContextualizedFirstName("Jean-Pierre", Continent.EUROPE),
        ContextualizedFirstName("Dimitri", Continent.EUROPE),
        ContextualizedFirstName("Jérémie", Continent.EUROPE),
        ContextualizedFirstName("Louis", Continent.EUROPE),
        ContextualizedFirstName("Thomas", Continent.EUROPE),
        ContextualizedFirstName("Dimitri", Continent.EUROPE),
        ContextualizedFirstName("Silvin", Continent.EUROPE),
        ContextualizedFirstName("Jérôme", Continent.EUROPE),
        ContextualizedFirstName("Guillaume", Continent.EUROPE),
        ContextualizedFirstName("Laurent", Continent.EUROPE),
        ContextualizedFirstName("Jean-Michel", Continent.EUROPE),
        ContextualizedFirstName("Philippe", Continent.EUROPE),
        ContextualizedFirstName("Nicolas", Continent.EUROPE),
        ContextualizedFirstName("Maxime", Continent.EUROPE),
        ContextualizedFirstName("Cédric", Continent.EUROPE),
        ContextualizedFirstName("Romain", Continent.EUROPE),
        ContextualizedFirstName("Théo", Continent.EUROPE),

        ContextualizedFirstName("Julien", Continent.EUROPE),
        ContextualizedFirstName("Bruno", Continent.EUROPE),
        ContextualizedFirstName("Sacha", Continent.EUROPE),
        ContextualizedFirstName("Anton", Continent.EUROPE),
        ContextualizedFirstName("Vadim", Continent.EUROPE),
        ContextualizedFirstName("Maxime", Continent.EUROPE),
        ContextualizedFirstName("Mikhail", Continent.EUROPE),
        ContextualizedFirstName("Alexei", Continent.EUROPE),
        ContextualizedFirstName("Samuel", Continent.EUROPE),
        ContextualizedFirstName("Didier", Continent.EUROPE),

        ContextualizedFirstName("Igor", Continent.EUROPE),
        ContextualizedFirstName("Ruslan", Continent.EUROPE),
        ContextualizedFirstName("Evgeniy", Continent.EUROPE),
        ContextualizedFirstName("Anatoliy", Continent.EUROPE),
        ContextualizedFirstName("Yuri", Continent.EUROPE),
        ContextualizedFirstName("Mischa", Continent.EUROPE),
        ContextualizedFirstName("Sacha", Continent.EUROPE),
        ContextualizedFirstName("Dmitriy", Continent.EUROPE),
        ContextualizedFirstName("Yevgeniy", Continent.EUROPE),
        ContextualizedFirstName("Liev", Continent.EUROPE),

        ContextualizedFirstName("Gianny", Continent.EUROPE),
        ContextualizedFirstName("Lucca", Continent.EUROPE),
        ContextualizedFirstName("Marco", Continent.EUROPE),
        ContextualizedFirstName("Giovanni", Continent.EUROPE),
        ContextualizedFirstName("Enzo", Continent.EUROPE),
        ContextualizedFirstName("Vinicio", Continent.EUROPE),
        ContextualizedFirstName("Milo", Continent.EUROPE),
        ContextualizedFirstName("Guido", Continent.EUROPE),
        ContextualizedFirstName("Calogero", Continent.EUROPE),
        ContextualizedFirstName("Gianni", Continent.EUROPE),
        ContextualizedFirstName("Matteo", Continent.EUROPE),
        ContextualizedFirstName("Alessandro", Continent.EUROPE),

        ContextualizedFirstName("Milen", Continent.EUROPE),
        ContextualizedFirstName("Yavor", Continent.EUROPE),
        ContextualizedFirstName("Stoyan", Continent.EUROPE),
        ContextualizedFirstName("Boyko", Continent.EUROPE),
        ContextualizedFirstName("Bojan", Continent.EUROPE),
        ContextualizedFirstName("Gojko", Continent.EUROPE),
        ContextualizedFirstName("Stefan", Continent.EUROPE),

        ContextualizedFirstName("Enrico", Continent.EUROPE),
        ContextualizedFirstName("Frederico", Continent.EUROPE),
        ContextualizedFirstName("Arsene", Continent.EUROPE),
        ContextualizedFirstName("Alohnzo", Continent.EUROPE),
        ContextualizedFirstName("Ramone", Continent.EUROPE),
        ContextualizedFirstName("Pietro", Continent.EUROPE),
        ContextualizedFirstName("Javi", Continent.EUROPE),

        ContextualizedFirstName("Sonny", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Barack", Continent.NORTH_AMERICA),
        ContextualizedFirstName("David", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Kevin", Continent.NORTH_AMERICA),
        ContextualizedFirstName("John", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Jacob", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Liam", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Sean", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Connor", Continent.NORTH_AMERICA),
        ContextualizedFirstName("James", Continent.NORTH_AMERICA),
        ContextualizedFirstName("George", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Glenn", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Matthew", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Jerry", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Mitt", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Milton", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Jorrel", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Meryle", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Karson", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Dayshaun", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Shaquile", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Jarmaine", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Rhody", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Dwade", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Podrick", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Teal", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Dejon", Continent.NORTH_AMERICA),
        ContextualizedFirstName("D’Amico", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Davon", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Lavar", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Marv", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Melvin", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Latrell", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Dylan", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Deion", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Jaycee", Continent.NORTH_AMERICA),
        ContextualizedFirstName("Darrence", Continent.NORTH_AMERICA),

        ContextualizedFirstName("Adriano", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Alejandro", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Alberto", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Alberto", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Esteban", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Abraão", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Alfonso", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Javier", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Angel", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Sergio", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Diego", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Hernán", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Héctor", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Jesús", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Carlos", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Cruz", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Junipero", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Ricardo", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Cruzito", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Atahualpa", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("João", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Antônio", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Augusto", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Benício", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Bento", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Bruno", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("Caio", Continent.SOUTH_AMERICA),
        ContextualizedFirstName("César", Continent.SOUTH_AMERICA),

        ContextualizedFirstName("Jomdah", Continent.AUSTRALIA),
        ContextualizedFirstName("Mallinbilly", Continent.AUSTRALIA),
        ContextualizedFirstName("Bilaranora", Continent.AUSTRALIA),
        ContextualizedFirstName("Naibar", Continent.AUSTRALIA),
        ContextualizedFirstName("Guemajarry", Continent.AUSTRALIA),
        ContextualizedFirstName("Linjah", Continent.AUSTRALIA),
        ContextualizedFirstName("Drell", Continent.AUSTRALIA),
        ContextualizedFirstName("Kaawa", Continent.AUSTRALIA),
        ContextualizedFirstName("Yarran", Continent.AUSTRALIA),
        ContextualizedFirstName("Isley", Continent.AUSTRALIA),
        ContextualizedFirstName("Omeo", Continent.AUSTRALIA),
        ContextualizedFirstName("Thono", Continent.AUSTRALIA),
        ContextualizedFirstName("Kinta", Continent.AUSTRALIA),
        ContextualizedFirstName("Paratyl", Continent.AUSTRALIA),
        ContextualizedFirstName("Teangi", Continent.AUSTRALIA),
        ContextualizedFirstName("Noah", Continent.AUSTRALIA),
        ContextualizedFirstName("William", Continent.AUSTRALIA),
        ContextualizedFirstName("Josh", Continent.AUSTRALIA),
        ContextualizedFirstName("Jack", Continent.AUSTRALIA),
        ContextualizedFirstName("Ethan", Continent.AUSTRALIA),
        ContextualizedFirstName("Mason", Continent.AUSTRALIA),
        ContextualizedFirstName("Harrison", Continent.AUSTRALIA),
        ContextualizedFirstName("Elijah", Continent.AUSTRALIA),
        ContextualizedFirstName("Hudson", Continent.AUSTRALIA),
        ContextualizedFirstName("Cooper", Continent.AUSTRALIA),
        ContextualizedFirstName("Logan", Continent.AUSTRALIA),
        ContextualizedFirstName("Archer", Continent.AUSTRALIA),
        ContextualizedFirstName("Riley", Continent.AUSTRALIA),

        ContextualizedFirstName("Gidja", Continent.AUSTRALIA),
        ContextualizedFirstName("Vaea", Continent.AUSTRALIA),
        ContextualizedFirstName("Temoe", Continent.AUSTRALIA),
        ContextualizedFirstName("Manua", Continent.AUSTRALIA),
        ContextualizedFirstName("Teiki", Continent.AUSTRALIA),
        ContextualizedFirstName("Rahiti", Continent.AUSTRALIA),
        ContextualizedFirstName("Aata", Continent.AUSTRALIA),
        ContextualizedFirstName("Heimanu", Continent.AUSTRALIA),
    )
}
