package gsalaun.diverse.utils

enum class SignUpStatus {
    SUCCESS,
    ACCOUNTALREADYEXIST,
    INVALIDPHONENUMBER,
    INVALIDFIRSTNAME,
    INVALIDLASTNAME,
    INVALIDTITLECODE,
    INVALIDEMAIL,
    INVALIDPASSWORD,
    ERROR
}